
#数据库配置
spring:
  sql:
    init:
      encoding: utf-8
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
      continue-on-error: true

  jpa:
#    show-sql: true
#    format-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.community.dialect.SQLiteDialect
    database-platform: org.hibernate.community.dialect.SQLiteDialect
  #      format-sql: true
  servlet:
    multipart:
      enabled: true
      #允许上传的单个文件大小
      max-file-size: 5GB
      #每次上传请求允许的文件总大小
      max-request-size: 6GB
#  datasource:
#    driver-class-name: org.sqlite.JDBC
#    url: jdbc:sqlite:sqlite/gold.sqlite

server:
  port: 580
